### ISSUE TITLE
pygustus error

### ISSUE THREAD

**Issue by CongLiu37** [Gaius-Augustus/GALBA#10]
Hello, 

I encountered following error with pyaugustus when running test1:
```
# Thu Mar  2 11:27:42 2023: Log information is stored in file /home/c/c-liu/Softwares/GALBA/example/tests/test1/GALBA.log
[M::mp_idx_restore@0.597*0.13] loaded the index
[M::mp_idx_print_stat] 280767 distinct k-mers; mean occ of infrequent k-mers: 1.52; 0 frequent k-mers accounting for 0 occurrences
[M::worker_pipeline::0.779*0.85] mapped 259 sequences
[M::main] Version: 0.7-r216-dirty
[M::main] CMD: /home/c/c-liu/Softwares/miniprot//miniprot -ut8 --gtf /home/c/c-liu/Softwares/GALBA/example/tests/test1/genome.mpi /home/c/c-liu/Softwares/GALBA/example/tests/../proteins.fa
[M::main] Real time: 0.783 sec; CPU: 0.667 sec; Peak RSS: 0.070 GB
#*********
# WARNING: Number of reliable training genes is low (226). Recommended are at least 600 genes
#*********
ERROR in file /home/c/c-liu/Softwares/GALBA/scripts/galba.pl at line 4895
Failed to execute: /home/c/c-liu/miniconda3/bin//python3 /home/c/c-liu/Softwares/GALBA/example/tests/test1/pygustus_hints.py 1> /home/c/c-liu/Softwares/GALBA/example/tests/test1/pygustus_hints.out 2>/home/c/c-liu/Softwares/GALBA/example/tests/test1/errors/pygustus_hints.err

real	0m23.895s
user	0m15.373s
sys	0m3.113s
```
and here is the error message for pyaugustus_hints.py:
```
Traceback (most recent call last):
  File "/home/c/c-liu/Softwares/GALBA/example/tests/test1/pygustus_hints.py", line 9, in <module>
    augustus.predict('/home/c/c-liu/Softwares/GALBA/example/tests/test1/genome.fa', species='Sp_1', partitionLargeSequences=True, partitionHints=True, minSplitSize=1000000, chunksize=2500000, jobs=8, **augargs)
  File "/home/c/c-liu/miniconda3/lib/python3.9/site-packages/pygustus/augustus.py", line 42, in predict
    pygustus_options = util.get_options(
  File "/home/c/c-liu/miniconda3/lib/python3.9/site-packages/pygustus/util.py", line 115, in get_options
    options = AugustusOptions(
  File "/home/c/c-liu/miniconda3/lib/python3.9/site-packages/pygustus/options/aug_options.py", line 87, in __init__
    self.set_value(option, value)
  File "/home/c/c-liu/miniconda3/lib/python3.9/site-packages/pygustus/options/aug_options.py", line 101, in set_value
    raise ValueError(
ValueError: Invalid Parameter for Augustus: partitionLargeSequences
```

Sincerely,

Cong

**Comment by KatharinaHoff** [comment]
Are you using the container? Are you using the latest container version?

If not, please update the container/use the container.

If you are running outside the container, you have to update your Augustus to
the latest code in the master branch on Github. There is a typo in a json
file that causes the problem.

Cong Liu ***@***.***> schrieb am Do. 2. März 2023 um 03:35:

**Comment by CongLiu37** [comment]
Works now. Thank you!
